-- Migration: 016_add_monthly_billing_fields
-- Description: Adds uppercase billing fields and auto-generated BILLKEY.

ALTER TABLE bills 
ADD COLUMN IF NOT EXISTS "BILLKEY" TEXT GENERATED ALWAYS AS ('BBPT--' || LPAD(id::text, 10, '0')) STORED,
ADD COLUMN IF NOT EXISTS "CUSTOMERNAME" TEXT,
ADD COLUMN IF NOT EXISTS "CUSTOMERTIN" TEXT,
ADD COLUMN IF NOT EXISTS "CUSTOMERBRANCH" TEXT,
ADD COLUMN IF NOT EXISTS "REASON" TEXT,
ADD COLUMN IF NOT EXISTS "THISMONTHBILLAMT" NUMERIC(15,2),
ADD COLUMN IF NOT EXISTS "PENALTYAMT" NUMERIC(15,2),
ADD COLUMN IF NOT EXISTS "DRACCTNO" TEXT,
ADD COLUMN IF NOT EXISTS "CRACCTNO" TEXT;

-- Index for BILLKEY for faster lookups
CREATE INDEX IF NOT EXISTS idx_bills_billkey ON bills("BILLKEY");
